# ============================
#        Builder Image
# ============================
FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN <<EOF
CGO_ENABLED=0 GOOS=linux GOARCH=amd64  \
  go build -o /worker ./cmd/worker
EOF

# ============================
#        Runtime Image
# ============================
FROM gcr.io/distroless/base:nonroot

WORKDIR /

COPY --from=builder /worker /worker

USER nonroot:nonroot

ENTRYPOINT ["/worker"]
