CREATETABLEIFNOTEXISTSjobs(
  job_idTEXTPRIMARYKEY,
  client_idTEXTNOTNULL,
  iterationsINTEGERNOTNULL,
  statusINTEGERNOTNULL,
  created_atTIMESTAMPWITHTIMEZONENOTNULL,
  updated_atTIMESTAMPWITHTIMEZONENOTNULL
);
